### ISSUE TITLE
Factor labels are incorrect when interpreting the rates??

### ISSUE THREAD

**Issue by watkilj** [josiahpjking/DasGuptR#5]
In the readme.md file, it says that "The returning rates and decomposition effects are age-sex specific". You then say "We can extract these population rates with the DasGupt_rates() function, which simply groups by \alpha (the factor not being adjusted for), sums, and reshapes". This implies that the factor column tells you which factor HAS NOT been standardized. However, since crude rates are the weighted means, these are the result of the product of the observed rate X standardized rate in the dgnpop results. Thus, in a two-factor setting (say pop_str rate and prevalence rate), you could divide the "values" column in the dgnpop table by the observed pop_str rate to see what the standardized prevalence rate is within each subpopulation and across populations. Conversely, you could divide by the observed prevalence rate to identify the standardized pop_str rate within each subpopulation and across populations. In the example you give in the readme.md file, this would be attuned to doing the following:

reconv_DG.2f <- dgnpop(df=reconv,
                    pop=year,prevalence, pop_str,
                    id_vars=c("Age","Sex"),ratefunction="prevalence*pop_str")

decomp.sub.2f = reconv_DG.2f[,c('factor','subpop',colnames(reconv_DG.2f)[which(stringr::str_detect(colnames(reconv_DG.2f), "pop_")==TRUE)])]

decomp.sub.2f.t = tidyr::pivot_longer(decomp.sub.2f, pop_2004:pop_2016)
decomp.sub.2f.t$year = as.numeric(stringr::str_remove(decomp.sub.2f.t$name, "pop_"))

reconv$subpop = stringr::str_remove_all(paste(reconv$Age, reconv$Sex, sep=""), "\\s")

decomp.sub.2f.t2 = left_join(decomp.sub.2f.t, reconv, by=c('year'='year','subpop'='subpop'))

decomp.sub.2f.t2$standard.prev = decomp.sub.2f.t2$value / decomp.sub.2f.t2$pop_str
decomp.sub.2f.t2$standard.pop = decomp.sub.2f.t2$value / decomp.sub.2f.t2$prevalence

Now, looking at the decomp.sub.2f.t2 and factor=="pop_str", you can see that the variable "standard.pop" is more or less constant within each subpopulation (some rounding) while "standard.prev" is not nearly constant. This implies that the "pop_str" has actually been standardized, not the "prevalence" variable, which contradicts your description noted above "which simply groups by \alpha (the factor not being adjusted for), sums, and reshapes"!

**Comment by josiahpjking** [comment]
apologies for the delay with fixing this. neither I nor Ben work much in this area any more and so it's a lot harder to get back into the right frame of mind to think about decomposition/standardisation etc, and neither of us have very much time these days. 

i couldn't quite figure out your issue as it sounded like possibly a conflation of DG's descriptions of decomposed rates (which kind of feel back to front to me), and the labelling of the factors. 

Thanks to a recent email from another user which prompted us to look at the package and notice this issue - there _is_ an issue with the labelling of the factors, which is currently fixed in the develop branch.  
`devtools::install_github("josiahpjking/DasGuptR@develop")`

i have a vague (optimistic) hope that we can do some more thorough testing and improvement before pushing this to main, but if we haven't found time in the next few weeks we'll move what we do have across.
